volumes:
  blackmouth:
  db_data:

# x-shared_environment: &shared_environment
#   LOG_LEVEL: ${LOG_LEVEL:-debug}
#   DATABASE_HOST: db
#   DATABASE_NAME: vapor_database
#   DATABASE_USERNAME: vapor_username
#   DATABASE_PASSWORD: vapor_password
  
services:
  app:
    image: blackmouthbackend:latest
    build:
      context: .
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      DATABASE_HOST: db
      DATABASE_NAME: blackmouth
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
    depends_on:
      - db
    ports:
      - '8080:8080'
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]

  db:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blackmouth
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    ports:
      - '3312:3306'
