name : Docker build

on:
  push:
    branches:
      - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              run: docker login -u 151019ardagulercito -p ArdaGulercito1910

            - name: Docker build
              run: docker build -t 151019ardagulercito/backend-blackmouth:latest .

            - name: Docker push 
              run: docker push 151019ardagulercito/backend-blackmouth:latest

            - name: Ejecutar migración en DigitalOcean
              run: |
                docker run --rm \
                  -e DATABASE_HOST=${{ secrets.DATABASE_HOST }} \
                  -e DATABASE_PORT=${{ secrets.DATABASE_PORT }} \
                  -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} \
                  -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
                  -e DATABASE_NAME=${{ secrets.DATABASE_NAME }} \
                  151019ardagulercito/backend-blackmouth:latest \
                  swift run BlackMouthBackend migrate --yes