name : Docker build

on:
  push:
    branches:
      - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              run: docker login -u 151019ardagulercito -p ArdaGulercito1910

            - name: Docker build
              run: docker build -t 151019ardagulercito/Backend-BlackMouth:latest .

            - name: Docker push 
              run: docker push 151019ardagulercito/Backend-BlackMouth:latest