name : Docker build

on:
  push:
    branches:
      - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              run: docker login -u ${{secrets.DOCKER_USER}} -p "${{secrets.DOCKER_PASSWORD}}"

            - name: Docker build
              run: docker build -t .

            - name: Docker push #nombre del repositorio en Docker Hub
              run: docker push #nombre del repositorio en Docker Hub